### ISSUE TITLE
Theo should be valid HTML (or almost valid)

### ISSUE THREAD

**Issue by loomchild** [loomchild/theo-rails#5]
## Background
The `.theo` syntax should be valid HTML, or at least close to it, so most parsers such as web browser or GitHub markdown processor, won't get confused. The current `<_button>` syntax is incorrect, since a custom element name must start with a letter (see [reference](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name)). Also, the component `<Button>` syntax is technically invalid, since it starts with uppercase (but it seems to be parsed well). 

Attribute name syntax, on the other hand, is more permissive (see [reference](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2)), but for custom elements specifically it's more restrictive (see [this reply](https://stackoverflow.com/a/53563849/4619705), [reference](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-core-concepts) and [XML spec](https://www.w3.org/TR/xml/#sec-common-syn)).

### 1. Suffix
Originally, we used `-partial` syntax (e.g. `<button-partial`>), that produced valid custom elements thanks to a `-`. Partials are also unambiguous and easy to grep. They also guarantee that the partial name won't clash with any standard HTML tag names. On the other hand, it was too verbose (see #2).

We could shorten it, by allowing a `-p` suffix as equivalent for `-partial`. But this is not self-explicit.

Or perhaps better, use a special suffix symbol, such as `@`, `%` or `_`. Although it's not technically correct, many HTML parsers seem to accept it.

We could also allow the user to specify a suffix, similar to [TailwindCSS prefix](https://tailwindcss.com/docs/configuration#prefix). It might be necessary in the future to cover edge cases, but I prefer to focus on default syntax for now, as it'll be the most widely used. 

### 2. Valid prefix
We could use a valid, unique prefix, such as `<theo:button />` or `<partial:button />`. It can be too verbose and make the code harder to read.

### 3. Marker attribute
We could add a special attribute to a partial tag, e.g. `<button partial />`. This will make the code shorter only if the element has content. On the other hand, it won't avoid name clash with a standard HTML element.

### 4. Implicit
Any unrecognized HTML element will be treated as partial. This produces the shortest syntax, and other frameworks such as Vue.js are doing it as well.

On the other hand, it can be ambiguous, especially since Rails encourages single-word partial names (e.g. `_form` in scaffold) and form helpers would clash with HTML form elements (`label`, `select`). We could combine this solution with a special attribute, such as `theo-off` or `no-partial` to distinguish them.

### 5. PascalCase
Require all partials to be invoked using pascal case, e.g `<Button />`. The convention of changing snake_case to PascalCase is well-known in Ruby and also used in other libraries. On the other hand, HTML parsers should be case-insensitive, so it still won't prevent name clashes with existing HTML elements (e.g. `<Button>Click</Button>` will be displayed as HTML button before being processed by Theo.

### 1. Leave it as-is
The current syntax is readable and is well-supported by most parsers. On the other hand, it's very [ViewComponent](https://viewcomponent.org/) specific.

### 2. Implicit
Use the same syntax as for partials, but check whether a component is `defined?` before deciding whether render a component or normal partial.

### 1. Leave it as is
If most parser support the current syntax, leave it as is, since it plays nice with ERB. I suppose it works because stricter rules apply only to custom elements, and parsers don't care to distinguish them from standard elements.

### 2. Use `:` prefix, similar to Vue.js 
This will produce a valid custom element in HTML and will be easier to learn for developers coming from Vue.js. On the other hand, it will clash with [Alpine.js shorthand syntax](https://alpinejs.dev/directives/bind#shorthand-syntax).

**Comment by DanielJackson-Oslo** [comment]
I disagree with the premise that it should be valid HTML. 

ERB is not valid HTML.
Phoenix components are not valid HTML.
Laravel Blade is not valid HTML.

In fact, it's a bonus that it's not valid HTML, as that means there can be no conflict between Theo Partials and actual HTML.

**Comment by loomchild** [comment]
@DanielJackson-Oslo Thanks for jumping into a discussion so quickly, I really appreciate it! I added more detail to the description - please make sure to re-read it. Please note that I opened this issue in response to #4.

I agree with you that it doesn't have to be valid HTML. Furthermore, it shouldn't be, since as you said, it can clash with existing front-end technology like WebComponents, Alpine.js, Vue.js, etc. Even though it seems like an edge case to have the same front-end component and partial name - but it will still be difficult to distinguish them when reading the code.

On the other hand, the fact that most HTML parsers get confused, still bothers me.

What are your thoughts on making the syntax almost-valid, to keep most parsers happy (browsers, code highlight, etc.), but avoiding name conflicts? For example, I somewhat like the suffix idea (`<button@ />`).

**Comment by loomchild** [comment]
(I added "2. Valid prefix" above)

**Comment by matthewblott** [comment]
@loomchild that `<button@ />` syntax just looks plain wrong to my eyes.

**Comment by DanielJackson-Oslo** [comment]
@matthewblott To me <theo:button /> is OK, but not as nice as <_button />

I really like the parallell between the filename of a partial starting with underscore: "_button.html.theo" and using the very same convention in my markup. 

Of course that means syntax highlighting breaks, but syntax highlighting will have to learn Theo anyway. 

As far as I understand, you want a browser to be able to parse it, so you can preview the design and work on HTML+CSS without running Rails? How do you do that with ERB today? 

Surely that's impossible for all but the most basic partials anyway? 

Having it be <theo:button class="btn" /> might work, sort of, but <theo:list collection%="Model"> won't work, as it of course won't spit out the list. It will just look like a div?

**Comment by DanielJackson-Oslo** [comment]
> @DanielJackson-Oslo Thanks for jumping into a discussion so quickly, I really appreciate it! I added more detail to the description - please make sure to re-read it. Please note that I opened this issue in response to #4.
> 
> I agree with you that it doesn't have to be valid HTML. Furthermore, it shouldn't be, since as you said, it can clash with existing front-end technology like WebComponents, Alpine.js, Vue.js, etc. Even though it seems like an edge case to have the same front-end component and partial name - but it will still be difficult to distinguish them when reading the code.
> 
> On the other hand, the fact that most HTML parsers get confused, still bothers me.
> 
> What are your thoughts on making the syntax almost-valid, to keep most parsers happy (browsers, code highlight, etc.), but avoiding name conflicts? For example, I somewhat like the suffix idea (`<button@ />`).

I think the main quest here should be to create a syntax highlighting library to go along with Theo, so you are free to create the best developer experience and most beautiful code, without having to be limited by the existing syntax highlighting. 

To me the rationale of Theo is to make my view code beautiful, composable, and make me happy just by looking at it. 

`<_button>` matching `_button.hml.theo` makes me happy in a way that `<theo:button>` or `<button_>` or `<button-partial>` doesn't. 

I also really love that CamelCase is reserved for ViewComponents in the current version. That just feels so _nice_ to go from the god awful ugly `<%= render(MessageListComponent.new) %>` to `<MessageList />`. My god it's SO MUCH NICER. And still using the same CamelCase as we would for a ViewComponent! I really love it. 

That said, CamelCase would look nice for partials too, but I don't refer to my partials in CamelCase anywhere else. It would make it easy to transition from React/JSX though.

**Comment by matthewblott** [comment]
Technically `ThisIsCalledPascalCase` and is named thus to avoid confusion with `thisThatIsCamelCase`. This distinction doesn't always matter but it means a lot more with front end templating.

This is really a design decision. I laid out my opposition to the underscore in #4 but not everyone will feel the same.

I assume there's agreement with using angle brackets? What is the issue with using `PascalCase` which would make Theo consistent with other component frameworks?

**Comment by loomchild** [comment]
Thanks a lot for sharing your opinions guys, I'll try to invite a few more people to express theirs and will decide in a week or two. 

I am thinking that perhaps we could have two alternative syntaxes (similar to other libraries), but I prefer to avoid complicating things now, and I believe that the defaults are very important.

(cheers for clarifying the distinction between camelCase and PascalCase - I corrected the issue description)

**Comment by loomchild** [comment]
Regarding PascalCase - it will still be problematic when partial name clashes with HTML element name (e.g. `<Form>`, `<Button>`) - but perhaps it's not a big deal since nobody writes HTML in uppercase these days.

**Comment by matthewblott** [comment]
I'm old enough to remember the earliest websites and the HTML was always written like this:
```html
<TABLE>
  <TR>
    <TD><INPUT TYPE="TEXT" VALUE="One"></TD>
    <TD><INPUT TYPE="TEXT" VALUE="Two"></TD>
    <TD><INPUT TYPE="TEXT" VALUE="Buckle"></TD>
    <TD><INPUT TYPE="TEXT" VALUE="Shoe"></TD>
  </TR>
</TABLE>
```

I've never seen pascal case used for vanilla HTML, only ever a component framework like React or Svelte.

**Comment by loomchild** [comment]
I am currently thinking of supporting both notations:
- `<_button />` (for the aesthetic, if user doesn't care about HTML parsers)
- `<Button />` (familiar for React and Vue.js developers and parser friendly)

**Comment by matthewblott** [comment]
@loomchild sounds like a plan 🙂

**Comment by DanielJackson-Oslo** [comment]
> I am currently thinking of supporting both notations:
> 
> * `<_button />` (for the aesthetic, if developer doesn't care about HTML parsers)
> * `<Button />` (familiar for React and Vue.js developers and parser friendly)

I think you should only pick one. <Button /> is fine by me, even though I prefer <_button>, but I think it's better to just have one. 

The menu is omakase, after all. One standard means one less decision to make.

**Comment by loomchild** [comment]
I backtracked on this one and will still allow `<_partial />` syntax because it looks nicer to me. It will use kebab case to be more similar to HTML, e.g. `<_some-partial />`.

Alternatively, pascal case like `<SomePartial />` will also be allowed, and it will be required for ViewComponents.

**Comment by matthewblott** [comment]
The easiest solution if Theo gets popular - see which option people adopt and if one of them is hardly used then drop it!

**Comment by bluz71** [comment]
Hello,

I just discovered Theo (today), and I am very much liking what I am seeing.

Having dabbled on the JS side (React, Astro) with a few projects, I have found tooling invaluable. Tools such as: Prettier (formatting), Tailwind Language Server (completion) & Prettier for Tailwind (utility class re-ordering).

I have done some initial experiments with positive results:

- Configure my Neovim to assign HTML filetype to `*.html.theo` files (nice Tree-sitter highlighting)
- Use Prettier override to associate `*.html.theo` files with the `HTML` parser (nice formatting)
- Hook up [Tailwind Prettier](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier) to Prettier, hence work with Theo files (nice utility class re-ordering)
- Assign Tailwind LSP to HTML files, hence work with Theo files (nice auto-completion)

This is my `.prettierrc.json`:

```json
{
  "plugins": ["prettier-plugin-tailwindcss"],
  "bracketSpacing": true,
  "printWidth": 100,
  "semi": false,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false,
  "overrides": [
    {
      "files": "*.html.theo",
      "options": {
        "parser": "html"
      }
    }
  ]
}
```

This appears to all work great when using `<SomePartial />` JSX-like syntax.

However, Prettier via the standard HTML parser does **NOT work** once `<_some-partial />` is encountered.

So for me, Theo being as close to valid HTML is a **very important** aim as it allows Theo to piggy-back off existing proven tools such as Prettier and Tailwind for Prettier.

I believe it is very important to always have JSX-like syntax available (maybe even preferred).

My 2cents.

**Comment by loomchild** [comment]
Hi @bluz71. I am happy that you like it, and thanks a lot for sharing your experience and config.

The idea is that the code editors, highlighters and formatters will be eventually improved to support the new format. I use a simpler setup in NeoVim (no prettier, etc.) and it already works relatively well for me with underscore syntax (except highlighting). But yeah, that's why there's an alternative PascalCase syntax and is not going away (similar to Vue supporting two options). What I should do definitely is to rewrite the documentation to make the syntaxes equally prominent, so people are not discouraged to using Theo by unfamiliar and initially poorly supported syntax.
